#pragma once


#define RENDER_DEBUG_ON true
#define RENDER_DEBUG_AXES_LINE_WIDTH 1.0f
#define RENDER_DEBUG_BOX_COLOR V4_PURPLE
#define RENDER_DEBUG_BOX_LINE_WIDTH 0.4f
#define RENDER_DEBUG_CAPSULE_COLOR V4_RED
#define RENDER_DEBUG_CAPSULE_SEGMENTS 32
#define RENDER_DEBUG_CAPSULE_LINE_WIDTH 0.4f
#define RENDER_DEBUG_CONE_COLOR V4_GREEN
#define RENDER_DEBUG_CONE_SEGMENTS 32
#define RENDER_DEBUG_CONE_LINE_WIDTH 0.4f
#define RENDER_DEBUG_CYLINDER_COLOR V4_BLUE
#define RENDER_DEBUG_CYLINDER_RADIUS 30.0f
#define RENDER_DEBUG_CYLINDER_SEGMENTS 32
#define RENDER_DEBUG_CYLINDER_LINE_WIDTH 0.4f
#define RENDER_DEBUG_GIZMOS_LINE_WIDTH 0.4f
#define RENDER_DEBUG_GRID_LINE_WIDTH 0.05f
#define RENDER_DEBUG_GRID_EXTENT 4096
#define RENDER_DEBUG_GRID_SPACING 20
#define RENDER_DEBUG_GRID_COLOR V4_WHITE
#define RENDER_DEBUG_SPHERE_COLOR V4_YELLOW
#define RENDER_DEBUG_SPHERE_RADIUS 50.0f
#define RENDER_DEBUG_SPHERE_SEGMENTS 64
#define RENDER_DEBUG_SPHERE_LINE_WIDTH 0.4f
#define RENDER_LOD1_DISTANCE 1.0f
#define RENDER_LOD2_DISTANCE 5.0f
#define RENDER_LOD3_DISTANCE 10.0f
#define RENDER_MAX_FRAMES_IN_FLIGHT 3
#define RENDER_MAX_MODEL_INSTANCES 163840
#define RENDER_SPATIAL_STREAM_CHECK_INTERVAL 0.f // in seconds
#define RENDER_SPATIAL_STREAM_RADIUS 100000.0f
#define RENDER_TARGET_FPS 60

#define RENDER_PARAMS_MAP \
    X(b, RENDER_DEBUG_ON, "Debug Visualizations On", false, true, tooltip_PARAM_RENDER_DEBUG_ON) \
    X(f, RENDER_DEBUG_AXES_LINE_WIDTH, "Axes Line Width", 0.0f, 10.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_BOX_LINE_WIDTH, "Box Line Width", 0.0f, 10.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_CAPSULE_LINE_WIDTH, "Collison Capsule Line Width", 0.0f, 10.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_CAPSULE_SEGMENTS, "Collision Capsule Segments", 1.0f, 512.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_CONE_LINE_WIDTH, "Cone Line Width", 0.0f, 10.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_CONE_SEGMENTS, "Cone Segments", 1.0f, 512.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_CYLINDER_LINE_WIDTH, "Cylinder Line Width", 0.0f, 10.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_CYLINDER_RADIUS, "Cylinder Radius", 1.0f, 512.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_CYLINDER_SEGMENTS, "Cylinder Segments", 1.0f, 512.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_GIZMOS_LINE_WIDTH, "Gizmo Line Width", 0.0f, 5.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_GRID_EXTENT, "Extent (Grid)", 0.0f, 4096.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_GRID_LINE_WIDTH, "Line Thickness (Grid)", 0.0f, 5.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_GRID_SPACING, "Spacing (Grid)", 0.0f, 200.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_SPHERE_LINE_WIDTH, "Sphere Line Width", 0.0f, 10.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_SPHERE_RADIUS, "Sphere Radius", 1.0f, 512.0f, tooltip_EMPTY) \
    X(f, RENDER_DEBUG_SPHERE_SEGMENTS, "Sphere Segments", 1.0f, 64.0f, tooltip_EMPTY) \
    X(f, RENDER_LOD1_DISTANCE, "LOD1 Distance", 0.0f, 100000.0f, tooltip_PARAM_RENDER_LOD1_DISTANCE) \
    X(f, RENDER_LOD2_DISTANCE, "LOD2 Distance", 0.0f, 100000.0f, tooltip_PARAM_RENDER_LOD1_DISTANCE) \
    X(f, RENDER_LOD3_DISTANCE, "LOD3 Distance", 0.0f, 100000.0f, tooltip_PARAM_RENDER_LOD1_DISTANCE) \
    X(u, RENDER_MAX_FRAMES_IN_FLIGHT, "Max Frames In Flight", 1, 3, tooltip_EMPTY) \
    X(f, RENDER_MAX_MODEL_INSTANCES, "Max Model Instances", 0.0f, 163840.0f, tooltip_EMPTY) \
    X(f, RENDER_SPATIAL_STREAM_CHECK_INTERVAL, "Spatial Streaming Check Interval",    0.0001f, 5.0f, tooltip_PARAM_RENDER_SPATIAL_STREAM_CHECK_INTERVAL) \
    X(f, RENDER_SPATIAL_STREAM_RADIUS, "Spatial Streaming (Culling) Radius", 0.0f, 100000.0f, tooltip_PARAM_RENDER_SPATIAL_STREAM_RADIUS) \
    X(u, RENDER_TARGET_FPS, "Target FPS", 0, 240, tooltip_EMPTY)

#define RENDER_PARAMS_V4_MAP \
    X(v4, RENDER_DEBUG_BOX_COLOR, "Box Color", V4_BLACK, V4_WHITE, tooltip_EMPTY) \
    X(v4, RENDER_DEBUG_CAPSULE_COLOR, "Capsule Color", V4_BLACK, V4_WHITE, tooltip_EMPTY) \
    X(v4, RENDER_DEBUG_CONE_COLOR, "Cone Color", V4_BLACK, V4_WHITE, tooltip_EMPTY) \
    X(v4, RENDER_DEBUG_CYLINDER_COLOR, "Cylinder Color", V4_BLACK, V4_WHITE, tooltip_EMPTY) \
    X(v4, RENDER_DEBUG_GRID_COLOR, "Grid Color", V4_BLACK, V4_WHITE, tooltip_EMPTY) \
    X(v4, RENDER_DEBUG_SPHERE_COLOR, "Sphere Color", V4_BLACK, V4_WHITE, tooltip_EMPTY)
