#include "pch.h"
#include "scene/model_wgsl.h"
#ifdef __EMSCRIPTEN__
	const char* model_vertex_wgsl = 
	"@group(0) @binding(0) var<uniform> camera : CameraUBO;\n"
	"@group(0) @binding(2) var<storage, read> instances : array<InstanceData>;\n"
	"\n"
	"struct InstanceData {\n"
	"    model : mat4x4<f32>,\n"
	"    color : vec4<f32>,\n"
	"};\n"
	"\n"
	"struct CameraUBO {\n"
	"    view : mat4x4<f32>,\n"
	"    proj : mat4x4<f32>,\n"
	"};\n"
	"\n"
	"struct VertexOutput {\n"
	"    @builtin(position) position : vec4<f32>,\n"
	"    @location(0) fragNormal : vec3<f32>,\n"
	"    @location(1) fragTexCoord : vec2<f32>,\n"
	"    @location(2) fragColor : vec4<f32>,\n"
	"    @location(3) fragPos : vec3<f32>,\n"
	"};\n"
	"\n"
	"@vertex\n"
	"fn main(\n"
	"    @location(0) inPosition : vec3<f32>,\n"
	"    @location(1) inNormal   : vec3<f32>,\n"
	"    @location(2) inTexCoord : vec2<f32>,\n"
	"    @builtin(instance_index) instanceIndex : u32\n"
	") -> VertexOutput {\n"
	"    let inst = instances[instanceIndex];\n"
	"    let model = inst.model;\n"
	"\n"
	"    let mvp = camera.proj * camera.view * model;\n"
	"    var output : VertexOutput;\n"
	"    output.position = mvp * vec4<f32>(inPosition, 1.0);\n"
	"\n"
	"    let model3x3 = mat3x3<f32>(\n"
	"	    model[0].xyz,\n"
	"	    model[1].xyz,\n"
	"	    model[2].xyz\n"
	"	);\n"
	"	let normalMatrix = mat3x3<f32>(model[0].xyz, model[1].xyz, model[2].xyz);\n"
	"    output.fragNormal = normalMatrix * inNormal;\n"
	"\n"
	"    output.fragTexCoord = inTexCoord;\n"
	"    output.fragColor = inst.color;\n"
	"    output.fragPos = (model * vec4<f32>(inPosition, 1.0)).xyz;\n"
	"\n"
	"    return output;\n"
	"}\n";

	const char* model_fragment_wgsl = 
	"struct DirectionalLight {\n"
	"    direction : vec3<f32>,\n"
	"    color : vec3<f32>,\n"
	"    intensity : f32,\n"
	"};\n"
	"\n"
	"struct PointLight {\n"
	"    position : vec3<f32>,\n"
	"    color : vec3<f32>,\n"
	"    intensity : f32,\n"
	"    constant : f32,\n"
	"    linear : f32,\n"
	"    quadratic : f32,\n"
	"};\n"
	"\n"
	"struct LightingUBO {\n"
	"    ambient : vec3<f32>,\n"
	"    dirLight : DirectionalLight,\n"
	"    numPointLights : i32,\n"
	"    pointLights : array<PointLight, 4>,\n"
	"    viewPos : vec3<f32>,\n"
	"};\n"
	"\n"
	"@group(0) @binding(1) var<uniform> lighting : LightingUBO;\n"
	"\n"
	"struct VertexOutput {\n"
	"    @builtin(position) position : vec4<f32>,\n"
	"    @location(0) fragNormal : vec3<f32>,\n"
	"    @location(1) fragTexCoord : vec2<f32>,\n"
	"    @location(2) fragColor : vec4<f32>,\n"
	"    @location(3) fragPos : vec3<f32>,\n"
	"};\n"
	"\n"
	"@fragment\n"
	"fn main(in : VertexOutput) -> @location(0) vec4<f32> {\n"
	"    let norm = normalize(in.fragNormal);\n"
	"    let viewDir = normalize(lighting.viewPos - in.fragPos);\n"
	"    let base = in.fragColor.rgb;\n"
	"\n"
	"    var result = base * lighting.ambient;\n"
	"\n"
	"    // Directional light\n"
	"    {\n"
	"        let lightDir = normalize(lighting.dirLight.direction);\n"
	"        let diff = max(dot(norm, lightDir), 0.0);\n"
	"        let diffuse = diff * base * lighting.dirLight.color * lighting.dirLight.intensity;\n"
	"\n"
	"        let halfDir = normalize(lightDir + viewDir);\n"
	"        let spec = pow(max(dot(norm, halfDir), 0.0), 32.0);\n"
	"        let specular = spec * lighting.dirLight.color * lighting.dirLight.intensity * 0.5;\n"
	"\n"
	"        result += diffuse + specular;\n"
	"    }\n"
	"\n"
	"    // Point lights\n"
	"    for (var i = 0; i < lighting.numPointLights && i < 4; i++) {\n"
	"        let p = lighting.pointLights[i];\n"
	"        let toLight = p.position - in.fragPos;\n"
	"        let dist = length(toLight);\n"
	"        let lightDir = normalize(toLight);\n"
	"\n"
	"        let attenuation = 1.0 / (p.constant + p.linear * dist + p.quadratic * dist * dist);\n"
	"\n"
	"        let diff = max(dot(norm, lightDir), 0.0);\n"
	"        let diffuse = diff * base * p.color * p.intensity * attenuation;\n"
	"\n"
	"        let halfDir = normalize(lightDir + viewDir);\n"
	"        let spec = pow(max(dot(norm, halfDir), 0.0), 32.0);\n"
	"        let specular = spec * p.color * p.intensity * 0.5 * attenuation;\n"
	"\n"
	"        result += diffuse + specular;\n"
	"    }\n"
	"\n"
	"    return vec4<f32>(result, in.fragColor.a);\n"
	"}\n";
#endif